pool: 
  name: "Azure pipelines"
  vmImage: "ubuntu-22.04"

trigger:
  - master

jobs:
  - job: myjob
    displayName: task1
    steps:
      - task: Maven@4
        inputs:
         mavenPOMFile: 'pom.xml'
         goals: package
         javaHomeOption: 'JDKVersion'
      - script: 
          echo hello world