---
pool:
  Vmimage: "ubuntu-latest"
  name: my-varspring

trigger:
  - main
parameters:
  name: spring
  type: string
  default: package
  values:
    - compile
    - test
    - package
    - build
    - deploy

variables:
- name: task
  value: Maven@4 
steps:
  - task: ${{ variables.task }} 
      inputs:
        mavenPOMFile: 'pom.xml'
        goals: ${{ parameters.spring }}
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        publishJUnitResults: true
        jdkVersionOption: '1.7'
