---
pool: 
  name: "Azure pipelines"
  vmImage: "ubuntu-22.04"

trigger:
  - main
variables:
- name: maven
  value: Maven@4
- name: output
  value: package
steps: 
  - task: $(variable.maven) 
    displayName: my-maven  
    inputs:
      mavenPOMFile: 'pom.xml' 
      goals: $(variable.output)
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      javaHomeOption: 'JDKVersion'