---
pool: 
  name: "Azure pipelines"
  vmImage: "ubuntu-latest"

trigger:
  - main
variables:
- name: task
  value: Maven@4
- name: goals
  value: package
steps: 
  - task: $(variable.task) 
    displayName: my-maven  
    inputs:
      mavenPOMFile: 'pom.xml'
      goals: $( variable.goals )
      testResultsFiles: "**/surefire-reports/TEST-*.xml."
      javaHomeOption: 'JDKVersion'