---
pool: 
  name: " Azure pipelines "
  vmImage: "ubuntu-20.4"

trigger:
  - main
steps: 
  - task: Maven@4
    displayName: my-maven  
    inputs:
      mavenPOMFile: 'pom.xml'
      goals: package
      testResultsFiles: "**/surefire-reports/TEST-*.xml."
      javaHomeOption: JDKVersion