---
pool:
  vmImage: 'ubuntu-latest'
  name: "Azure pipelines"

trigger: 
  - main

jobs:
  - job: software_installations
    displayName: openjdk11
    continueOnError: "false"
    steps:
      - task: Maven@3
        inputs:
          packagetype: 'mvn'
          version: JDKVersion
  - job: Build_job
    displayName : springpet-clinic
    dependsOn: software_installations
    steps:
      - task: Maven@3
        inputs: 
          command: "mvn package"
          mavenPOMFile: pom.xml.
  